version: '2'
services:
    portainer:
        container_name: portainer
        restart: always
        image: portainer/portainer:latest
        ports: 
            - '9000:9000'
        volumes:
            - 'data:/data'
            - '/var/run/docker.sock:/var/run/docker.sock'

volumes:
    data:    
