version: '2'
services:
    portainer:
        restart: always
        image: portainer/portainer:latest
        ports: 
            - '9000:9000'
        volumes:
            - 'portainer_data:/data'
            - '/var/run/docker.sock:/var/run/docker.sock'

volumes:
    portainer_data:    
